### PR TITLE
Fix memory leak in tests

### LINKED ISSUE #104: Memory Leak in Tests
I'm converting an Ember 1.13 app from ember-cli-ic-ajax to ember-ajax and my tests keep running out of memory. See the discussion below for the (likely) cause.

### PR DESCRIPTION
**Pull request by alexlafroscia**
Closes #104

### CODE REVIEW

**Comment by rwjblue** [comment]
@jamesarosen - Can you test this fix?

**Comment by jamesarosen** [comment]
Already did: https://github.com/ember-cli/ember-ajax/issues/104#issuecomment-217019134

The `=>` holds on to `this` still, which has a `container`.

**Comment by rwjblue** [comment]
Thank you, I missed that that comment was about this patch.

**Comment by alexlafroscia** [comment]
@jamesarosen I added the fix that you suggested, would you mind testing if that worked?

File: addon/ajax-request.js [hunk 1]
```diff
@@ -42,16 +42,17 @@ function isJSONAPIContentType(header) {
...
 
   constructor() {
     this.init();
   }
 
   init() {
-    this.pendingRequestCount = 0;
     if (testing) {
-      Test.registerWaiter(() => this.pendingRequestCount === 0);
+      Test.registerWaiter(() => (pendingRequestCount === 0));
```
Comment (jamesarosen) [inline addon/ajax-request.js]: This [compiles](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=Test.registerWaiter(()%20%3D%3E%20(pendingRequestCount%20%3D%3D%3D%200))%3B) to
```js
if (testing) {
  Test.registerWaiter(function () {
    return pendingRequestCount === 0;
  });
}
```
That's totally fine. But when browsers start honoring `=>` natively and we stop compiling, I worry that the callback will hold on to `this` unnecessarily. I don't see anything in the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions-runtime-semantics-evaluation) that tells me whether this would be true or not. I suspect it _won't_ be a problem since otherwise, every time a programmer did something like `setTimeout(() => { console.log('hi') })` it would leak memory. To be safe, you could write this in ES5 syntax.

**Comment by jamesarosen** [comment]
I ran a few subsets of our test suite and see no lingering `container`s :)

File: addon/ajax-request.js (hunk 1 above)
Comment (alexlafroscia) [inline addon/ajax-request.js]: Yeah, that probably makes more sense. Really good points; might as well do it the "safer" way.

**Comment by rwjblue** [comment]
Right now we are always adding a waiter for each instance, maybe we can just use a single waiter?

Something like the following:

```js
let pendingRequestCount = 0;

if (Ember.Test) {
  Ember.Test.registerWaiter(function() {
    return pendingRequestCount === 0;
  });
}
```

Then throughout the other locations where we use `this.pendingRequestCount++` or `this.pendingRequestCount--` we would just use `pendingRequestCount++` / `pendingRequestCount--`...

**Comment by alexlafroscia** [comment]
Alright, that's what I had before and changed it.  I'll roll back to the previous commit where it's just a global counter.

**Comment by alexlafroscia** [comment]
@jamesarosen @rwjblue alright, I rolled back to the version that 

- Uses a global counter instead of per-instance counters
- Actually seems to fix the problem
- Doesn't mess with `unregisterWaiter`

Does this seem like the best approach?

**Comment by jamesarosen** [comment]
I'm happy as-is. I'm intrigued by @rwjblue's idea of having a single, static waiter. It's not a blocker for our test-suite, though.

**Comment by alexlafroscia** [comment]
Oh yeah, that does make more sense. I mis-read what he was saying earlier.  I'll switch it around to that

**Comment by rwjblue** [comment]
LGTM
